language: python

python:
  - 2.7

before_install:
  - git submodule update --init --recursive

install:
  - pip install --requirement requirements.txt --use-mirrors

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - bash src/build_extension.sh
  - python src/testserver.py &
  - export SERVER_PID=$!

script:
  - lettuce

after_script:
 - kill -KILL $SERVER_PID
